$location = "WestEurope"
$osVhdUri = "https://blob1of1vhd1images.blob.core.windows.net/testcontainerc/vhddisk01Fix.vhd"
#$osVhdUri = "https://blob1of1vhd1images.blob.core.windows.net/testcontainerc/mdxt00000108Fix.vhd"
#$imageName = "TestVMBKXWinPE01"
$rgName = "TestVMForRPA"
$imageName = "TestVMBKXWin10"
$imageConfig = New-AzImageConfig -Location $location
$imageConfig = Set-AzImageOsDisk -Image $imageConfig -OsType Windows -OsState Generalized -BlobUri $osVhdUri
#$imageConfig = Set-AzImageOsDisk -Image $imageConfig -OsType Windows -OsState Specialized -BlobUri $osVhdUri 
$image = New-AzImage -ImageName $imageName -ResourceGroupName $rgName -Image $imageConfig